### ISSUE TITLE
Save an additional 5 bytes

### ISSUE THREAD

**Issue by rlauck** [xem/miniCodeEditor#9]
Give the iframe an id, and refer to the id instead of e.lastChild. Also, why not use a p element instead of x?

**Comment by xem** [comment]
# id

Did you try it?
If we try to access the iframe element with its id, it won't work on Chrome, because Chrome will return the iframe's window instead of the iframe element.

But indeed, on firefox (only), it can save 5 bytes.

# p

yeah, x could hhave been a p or any one-letter tag... the guy who thought of replacing body with an element chose "x" and it remained like this.

**Comment by rlauck** [comment]
Ah, my bad I only tested on Firefox assumed Chrome would return the element too.
